enable-module-update = true
parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true
cli-source = "MorpheApp/morphe-cli"

[YouTube-Anddea-NonRoot]
#app-name = "YouTube"
patches-source = "anddea/revanced-patches"
arch = "both"
included-patches = "'Hide Shorts dimming'"
patcher-args = "-e 'Hide shortcuts' -Oexplore=true -Oshorts=true -e 'Theme' -OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Anddea]
#app-name = "YouTube"
patches-source = "anddea/revanced-patches"
build-mode = "module"
included-patches = "'Hide Shorts dimming'"
patcher-args = "-e 'Hide shortcuts' -Oexplore=true -Oshorts=true -e 'Theme' -OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[GooglePhotos]
patches-source = "RookieEnough/De-ReVanced"
arch = "both"
included-patches = "'Enable DCIM folders backup control'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"
