enable-module-update = true
parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true

[YouTube-NonRoot]
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
arch = "both"
included-patches = "'Hide Shorts dimming'"
patcher-args = "-e 'Hide shortcuts' -Oexplore=true -Oshorts=true -e 'Theme' -OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube]
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "module"
included-patches = "'Hide Shorts dimming'"
patcher-args = "-e 'Hide shortcuts' -Oexplore=true -Oshorts=true -e 'Theme' -OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[GooglePhotos]
arch = "both"
included-patches = "'Enable DCIM folders backup control'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
