enable-module-update = true
parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true
cli-source = "MorpheApp/morphe-cli"
rv-brand = "ReVanced Extended"

[YouTube]
patches-source = "anddea/revanced-patches"
arch = "arm64-v8a"
included-patches = "'Hide Shorts dimming'"
patcher-args = "-e 'Hide shortcuts' -Oexplore=true -Oshorts=true -e 'Theme' -OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Root]
patches-source = "anddea/revanced-patches"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Hide Shorts dimming'"
patcher-args = "-e 'Hide shortcuts' -Oexplore=true -Oshorts=true -e 'Theme' -OdarkThemeBackgroundColor=#000000 -OlightThemeBackgroundColor=#FFFFFF"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Music]
patches-source = "anddea/revanced-patches"
arch = "arm64-v8a"
included-patches = "'Disable music video in album' 'Hide overlay filter' 'Hide player overlay filter'"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#000000"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Music-Root]
patches-source = "anddea/revanced-patches"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Disable music video in album' 'Hide overlay filter' 'Hide player overlay filter'"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#000000"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[GooglePhotos]
patches-source = "Akash-Sriram/morphe-google-photos"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Facebook]
patches-source = "SysAdminDoc/Hushfacebook"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"

[Messenger]
patches-source = "rushiranpise/morphe-patches"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"

[AdGuard]
patches-source = "rushiranpise/morphe-patches"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard/"
